version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    env_file:
      - ./.env

  postgres:
    image: postgres
    env_file:
      - ./.env

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
