version: "3"
services:
  api:
    image: suman196/dashapp
    depends_on:
      - postgres
    ports:
      - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    env_file:
      - ./.env

    environment:
      - database_hostname=postgres

  postgres:
    image: postgres
    env_file:
      - ./.env

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
