name: Deploy Backend To Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_PRIVATE_KEY}}
          
      - name: SSH into Droplet and update
        run: |
          ssh -o StrictHostKeyChecking=no -A root@64.227.166.179 "docker compose -f dashApp_BE/docker-compose-dev.yml down && sudo rm -rf dashApp_BE && git clone git@github.com:Suman196pokhrel/dashApp_BE.git && docker compose -f dashApp_BE/docker-compose-dev.yml up -d"
